name: CD

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: 'mynode:20'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build my Nodejs Docker image
        run: docker image build --tag="${IMAGE_NAME}" ./

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Linting
        run: docker container run "${IMAGE_NAME}" npm run lint

      # - name: Testing
      #   run: docker container run "${IMAGE_NAME}" npm test

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'pull_request' && needs.build.result == 'success'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: esgidocker
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: esgidocker/front-tp-chat-ci-cd:latest

  deploy_tag:
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/') && needs.build.result == 'success'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: esgidocker
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./
          tags: esgidocker/front-tp-chat-ci-cd:${{ github.ref_name }}
